# Basic attack config, use for basic debug
attack:
  pgd:
    eps: [1.5,1.5,0]
    alpha: [0.05, 0.05, 0.05] 
    steps: 1
    n_att: 1
    project: True
    colla_attack: False
    noise_attack: False
    save_attack: True
  save_path: 'save_attack/1013_PGD'
  attack_target: pred
  loss_type: _1013_PGD
